Update docs and links from old cloud version to current.
CoEDL/elpis_next pull request #51
Opened 2023-06-28 03:51 UTC by harrykeightley

2023-07-04 05:36 UTC, savitadatta requested changes

2023-07-04 05:36 UTC, savitadatta commented on docs/contributing.md
> +To prepare the server devlopment environment, [make sure you have Poetry installed](https://python-poetry.org/docs/),
development

2023-07-05 05:23 UTC, harrykeightley commented on docs/contributing.md
> +To prepare the server devlopment environment, [make sure you have Poetry installed](https://python-poetry.org/docs/),
Fixed in latest revision.

2023-07-07 01:43 UTC, savitadatta approved these changes

2023-07-07 21:49 UTC, merged